# See https://aka.ms/customizecOontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

# This stage is used when running from VS in fast mode (Default for Debug configuration)
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
EXPOSE 5216


# This stage is used to build the service project
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ENV SUPPRESS_VERSION_BUMP=1
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["StreetFinder.csproj", "./"]
RUN dotnet restore "StreetFinder.csproj"
COPY . .
RUN dotnet build -c $BUILD_CONFIGURATION -o /app/build

# This stage is used to publish the service project to be copied to the final stage
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./StreetFinder.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# This stage is used in production or when running from VS in regular mode (Default when not using the Debug configuration)
FROM base AS final
WORKDIR /app
ENV ASPNETCORE_HTTP_PORTS=5216
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "StreetFinder.dll"]
