//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StreetFinder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StreetFinder.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;update_date&quot;: &quot;2024-02-23T19:06:35.329595&quot;, &quot;data&quot;: [{&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;10TH ST&quot;, &quot;short_name&quot;: &quot;10TH&quot;}, {&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;11TH ST&quot;, &quot;short_name&quot;: &quot;11TH&quot;}, {&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;13TH ST&quot;, &quot;short_name&quot;: &quot;13TH&quot;}, {&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;14TH ST&quot;, &quot;short_name&quot;: &quot;14TH&quot;}, {&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;14TH ST E&quot;, &quot;short_name&quot;: &quot;14TH&quot;}, {&quot;zipcode_range&quot;: [22307, 22307], &quot;name&quot;: &quot;14TH ST W&quot;, &quot;short_name&quot;: &quot;14TH&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string streets {
            get {
                return ResourceManager.GetString("streets", resourceCulture);
            }
        }
    }
}
